AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - tmp/**/*
    - vendor/**/*
    - Guardfile
  Include:
    - lib/thor/**/*
  RunRailsCops: true

Documentation:
  Enabled: false

Encoding:
  Enabled: false

FileName:
  Exclude:
    - !ruby/regexp /(\d+)-(\w+)\.rb$/
    - !ruby/regexp /development\.rb$/

LineLength:
  Enabled: true
  Max: 140

MethodLength:
  Enabled: true
  Max: 30

NumericLiterals:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table

Rails/Output:
  Enabled: false

Style/TrailingBlankLines:
  EnforcedStyle: final_newline
  SupportedStyles:
    - final_newline
    - final_blank_line
